# environment.yml
name: rl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - gymnasium=0.29.1
  - stable-baselines3=2.1.0
  - pyyaml=6.0
  - tqdm=4.66.4
  - rich=13.7.0
  - tensorboard=2.20.0
  - pip
  - pip:
    - -r requirements.txt